name: Flutter Web Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - name: Get dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --base-href /gana_website/

      - name: Deploy to launchpad branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Create or checkout launchpad branch
          git fetch origin launchpad || true
          if git show-ref --quiet refs/heads/launchpad; then
            git checkout launchpad
          else
            git checkout -b launchpad
          fi

          # Remove old files
          git rm -rf .

          # Copy build files from build/web
          cp -r build/web/* .
          cp -r build/web/.* . 2>/dev/null || true

          # Commit & push
          git add .
          git commit -m "Deploy updated web build"
          git push origin launchpad --force

